export const metadata = { title: 'Privacy Policy — MyOrbisVoice' }

export default function PrivacyPage() {
  return (
    <main style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px', fontFamily: 'sans-serif', lineHeight: 1.7, color: '#1a1a1a' }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
      <p style={{ color: '#666', marginBottom: 40 }}>Last updated: April 30, 2026</p>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>1. Overview</h2>
        <p>MyOrbisVoice ("we", "our", or "us") operates the MyOrbisVoice platform, including the website at myorbisvoice.com and the application at app.myorbisvoice.com. This Privacy Policy explains how we collect, use, and protect your information when you use our services.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>2. Information We Collect</h2>
        <p><strong>Account information:</strong> Name, email address, business name, and password when you register.</p>
        <p style={{ marginTop: 12 }}><strong>Business information:</strong> Business profile details, operating hours, services, and configuration data you provide to set up your voice agents.</p>
        <p style={{ marginTop: 12 }}><strong>Communication data:</strong> Call transcripts, appointment records, and conversation summaries generated by your voice agents.</p>
        <p style={{ marginTop: 12 }}><strong>Integration credentials:</strong> OAuth tokens for Google Workspace (Gmail, Calendar) and connection credentials for third-party services. These are encrypted at rest and never exposed in plaintext.</p>
        <p style={{ marginTop: 12 }}><strong>Usage data:</strong> Log data, IP addresses, browser type, and feature usage for platform operation and improvement.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>3. How We Use Google User Data</h2>
        <p>When you connect a Google account to MyOrbisVoice, we request access to the following scopes:</p>
        <ul style={{ paddingLeft: 24, marginTop: 12 }}>
          <li><strong>gmail.send</strong> — to send booking confirmations, follow-up emails, and notifications on your behalf from your connected agent mailbox.</li>
          <li><strong>gmail.readonly</strong> — to read incoming emails relevant to appointments and customer inquiries handled by your voice agents.</li>
          <li><strong>calendar</strong> — to create, update, and cancel calendar appointments booked through your voice agents.</li>
          <li><strong>userinfo.email</strong> — to identify which Google account is connected and display connection status in your dashboard.</li>
        </ul>
        <p style={{ marginTop: 12 }}>We do not use Google user data for advertising, profiling, or any purpose beyond operating the features described above. We do not share Google user data with third parties except as required to operate the service (e.g. storing encrypted tokens in our database).</p>
        <p style={{ marginTop: 12 }}>Our use of data obtained through Google APIs complies with the <a href="https://developers.google.com/terms/api-services-user-data-policy" style={{ color: '#1a73e8' }}>Google API Services User Data Policy</a>, including the Limited Use requirements.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>4. How We Store and Protect Your Data</h2>
        <p>All data is stored in encrypted databases hosted on servers in the European Union. Integration credentials (OAuth tokens, API keys) are encrypted at rest using AES-256-GCM. We use HTTPS for all data in transit. Access to production systems is restricted to authorized personnel only.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>5. Data Sharing</h2>
        <p>We do not sell your personal data. We share data only with:</p>
        <ul style={{ paddingLeft: 24, marginTop: 12 }}>
          <li><strong>Service providers</strong> necessary to operate the platform (cloud hosting, telephony, AI model providers).</li>
          <li><strong>Legal authorities</strong> when required by law.</li>
        </ul>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>6. Data Retention</h2>
        <p>We retain your data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting us. Call transcripts and conversation logs are retained for 90 days by default and can be configured per your plan.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>7. Your Rights</h2>
        <p>Depending on your location you may have rights to access, correct, delete, or export your personal data. To exercise these rights, contact us at the address below.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>8. Cookies</h2>
        <p>We use session cookies and local storage to maintain your login state. We do not use third-party tracking cookies or advertising cookies.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>9. Changes to This Policy</h2>
        <p>We may update this policy from time to time. We will notify you of material changes by email or by posting a notice in the application. Continued use of the service after changes constitutes acceptance.</p>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12 }}>10. Contact</h2>
        <p>For privacy questions or data requests, contact us at:</p>
        <p style={{ marginTop: 8 }}><strong>MyOrbisVoice</strong><br />Email: privacy@myorbisvoice.com<br />Website: https://myorbisvoice.com</p>
      </section>
    </main>
  )
}
